<?php
/**
 * Copyright © MercadoPago. All rights reserved.
 *
 * @author      Bruno Elisei <brunoelisei@o2ti.com>
 * @license     See LICENSE for license details.
 */

/**
 * @var \MercadoPago\PaymentMagento\Block\Sales\Info\Pix $block
 * @see \MercadoPago\PaymentMagento\Block\Sales\Info\Pix
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$qrCode = isset($specificInfo['qr_code']) ? $specificInfo['qr_code']: null;
$qrCodeImage = isset($specificInfo['qr_code_base64']) ? $specificInfo['qr_code_base64'] : null;
$expirationDateQrcode = isset($specificInfo['date_of_expiration']) ? $specificInfo['date_of_expiration'] : null;
$payerDocumentIdentification =
    isset($specificInfo['payer_document_identification']) ?
        $specificInfo['payer_document_identification'] : null;
$ticketUrl = isset($specificInfo['ticket_url']) ? $specificInfo['ticket_url'] : null;
?>
<h4><?= /* @noEscape */ $title ?></h4>
<?php if ($specificInfo): ?>
    <div class="mercadopago-instruction pix">
        <?php if ($expirationDateQrcode): ?>
        <div class="instruction-information expiration">
            <div>
                <?= $block->escapeHtml(__('Your payment will be valid until')); ?>
            </div>
            <div class="expiration-date">
                <strong>
                    <?= /* @noEscape */ $block->formatDate($expirationDateQrcode, \IntlDateFormatter::MEDIUM, true) ?>
                </strong>
            </div>
        </div>
        <?php endif;?>
        <?php if ($qrCodeImage): ?>
            <div class="instruction-information qr-code-image">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('To pay, please scan the QR code')); ?>
                </div>
                <div class="qrcode-image">
                    <img src="data:image/png;base64,<?=  $block->escapeHtml($qrCodeImage) ?>"
                        alt="<?= /* @noEscape */ $title ?>" width="200" />
                </div>
            </div>
        <?php endif;?>
        <?php if ($qrCode): ?>
            <div class="instruction-information qr-code">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('or, if you prefer, copy-paste the code')); ?>
                </div>
                <div class="qrcode-text">
                    <textarea id="qr-code-value"
                        rows="10" cols="30" readonly><?= $block->escapeHtml($qrCode) ?></textarea>
                </div>
            </div>
        <?php endif;?>
        <?php if ($payerDocumentIdentification): ?>
            <div class="instruction-information ticket-more-information">
                <div class="label">
                    <?= $block->escapeHtml(__('Payer Document Identification')); ?>
                </div>
                <div class="value">
                    <?=  $block->escapeHtml($payerDocumentIdentification) ?>
                </div>
            </div>
        <?php endif;?>
        <?php if ($ticketUrl): ?>
            <div class="instruction-information link">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('Further instructions')); ?>
                </div>
                <div class="ticket-link">
                    <a target="_blank"
                        href="<?=  $block->escapeHtml($ticketUrl) ?>" 
                        alt="<?= /* @noEscape */ $title ?>"><?= $block->escapeHtml(__('Details for payment')); ?></a>
                </div>
            </div>
        <?php endif;?>
    </div>
<?php endif;?>
