<?php
/**
 * Copyright © MercadoPago. All rights reserved.
 *
 * @author      Bruno Elisei <brunoelisei@o2ti.com>
 * @license     See LICENSE for license details.
 */

/**
 * @var \MercadoPago\PaymentMagento\Block\Sales\Info\CheckoutPro $block
 * @see \MercadoPago\PaymentMagento\Block\Sales\Info\CheckoutPro
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$externalLink = isset($specificInfo['init_point']) ? $specificInfo['init_point'] : null;
$dateOfExpiration = isset($specificInfo['date_of_expiration']) ? $specificInfo['date_of_expiration'] : null;
?>
<h4><?= /* @noEscape */ $title ?></h4>
<?php if ($specificInfo): ?>
    <div class="mercadopago-instruction ticket">
        <?php if ($dateOfExpiration): ?>
            <div class="instruction-information expiration">
                <div>
                    <?= $block->escapeHtml(__('Your payment will be valid until')); ?>
                </div>
                <div class="expiration-date">
                    <strong>
                    <?= /* @noEscape */ $block->formatDate($dateOfExpiration, \IntlDateFormatter::MEDIUM, false) ?>
                    </strong>
                </div>
            </div>
        <?php endif;?>
        <?php if ($externalLink): ?>
            <div class="instruction-information link">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('Link for payment')); ?>
                </div>
                <div class="ticket-link">
                    <a target="_blank"
                        href="<?=  $block->escapeHtml($externalLink) ?>" 
                        alt="<?= /* @noEscape */ $title ?>"><?= $block->escapeHtml(__('Link for payment')); ?></a>
                </div>
            </div>
        <?php endif;?>
    </div>
<?php endif;?>
