
<?php
/**
 * Copyright © MercadoPago. All rights reserved.
 *
 * @author      Mercado Pago
 * @license     See LICENSE for license details.
 */

/**
 * @var MercadoPago\AdbPayment\Block\Order\Success\Additional $block
 * @see MercadoPago\AdbPayment\Block\Order\Success
 */
?>
<?php if ($block->getInfo('external_resource_url')): ?>
    <div class="mercadopago-payment-success-details">
        <div>
            <a href="<?= $block->escapeHtml($block->getInfo('external_resource_url')); ?>"
                target="_blank"
                class="action primary continue">
                <?= $block->escapeHtml(__('Details for payment')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
<div class="mercadopago-payment-logo">
    <img src="<?php echo $this->getViewFileUrl('MercadoPago_AdbPayment::images/core/logo.svg'); ?>"/>
</div>
