
<?php
/**
 * Copyright © MercadoPago. All rights reserved.
 *
 * @author      Bruno Elisei <brunoelisei@o2ti.com>
 * @license     See LICENSE for license details.
 */

/**
 * @var MercadoPago\PaymentMagento\Block\Order\Success\Additional $block
 * @see MercadoPago\PaymentMagento\Block\Order\Success
 */
$document = $block->getInfo('payer_document_identification');
?>
<div class="mercadopago-payment-success-details">
    <?= $block->escapeHtml(__('Agreement code with Mercado Pago')) ?> 
    <div class="field mercadopago-input-group">
        <div class="control _with-tooltip">
            <input type="text"
                id="line-code-value"
                value="<?= $block->escapeHtml($block->getInfo('financial_institution')); ?>"
                class="input-text mercadopago-input-small"/> 
            <div class="field-tooltip toggle">
                <button class="btn" id="copy-code" 
                    data-clipboard-action="copy" 
                    data-clipboard-target="#line-code-value">
                    <?= $block->escapeHtml(__('Copy')); ?>
                </button>
            </div>
        </div>
    </div>
    <?= $block->escapeHtml(
        __('Inform the Identification Document used in the purchase: %1', $document)
    ) ?>
    <div>
        <a href="<?= $block->escapeHtml($block->getInfo('external_resource_url')); ?>"
            target="_blank"
            class="action primary continue">
            <?= $block->escapeHtml(__('Details for pay')) ?> 
        </a>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#copy-code": {
            "widgetClipboard": {
                "enabled": true,
                "copiedtext": "<?= /* @noEscape */ __('Copied'); ?>",
                "textBtn": "<?= /* @noEscape */ __('Copy'); ?>"
            }
        }
    }
</script>