<?php
/**
 * Copyright © MercadoPago. All rights reserved.
 *
 * @author      Bruno Elisei <brunoelisei@o2ti.com>
 * @license     See LICENSE for license details.
 */

/**
 * @var \MercadoPago\PaymentMagento\Block\Sales\Info\Boleto $block
 * @see \MercadoPago\PaymentMagento\Block\Sales\Info\Boleto
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$barcode = isset($specificInfo['barcode']) ? $specificInfo['barcode']: null;
$lineCode = isset($specificInfo['line_code']) ? $specificInfo['line_code']: null;
$externalLink = isset($specificInfo['external_resource_url']) ? $specificInfo['external_resource_url'] : null;
$payerFirstName = isset($specificInfo['payer_first_name']) ? $specificInfo['payer_first_name'] : null;
$payerLastName = isset($specificInfo['payer_last_name']) ? $specificInfo['payer_last_name'] : null;
$dateOfExpiration = isset($specificInfo['date_of_expiration']) ? $specificInfo['date_of_expiration'] : null;
$payerDocumentIdentification =
    isset($specificInfo['payer_document_identification']) ?
        $specificInfo['payer_document_identification'] : null;
$verificationCode = isset($specificInfo['verification_code']) ? $specificInfo['verification_code'] : null;
$financialInstitution = isset($specificInfo['financial_institution']) ? $specificInfo['financial_institution'] : null;
?>
<h4><?= /* @noEscape */ $title ?></h4>
<?php if ($specificInfo): ?>
    <div class="mercadopago-instruction ticket">
        <?php if ($dateOfExpiration): ?>
            <div class="instruction-information expiration">
                <div>
                    <?= $block->escapeHtml(__('Your payment is valid until')); ?>
                </div>
                <div class="expiration-date">
                    <strong>
                    <?= /* @noEscape */ $block->formatDate($dateOfExpiration, \IntlDateFormatter::MEDIUM, false) ?>
                    </strong>
                </div>
            </div>
        <?php endif;?>
        <?php if ($lineCode): ?>
            <div class="instruction-information barcode">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('Line Code is')); ?>
                </div>
                <div class="ticket-text">
                    <textarea id="qr-code-value"
                        rows="3" cols="30" readonly><?= $block->escapeHtml($lineCode) ?></textarea>
                </div>
            </div>
        <?php endif;?>
        <?php if ($externalLink): ?>
            <div class="instruction-information link">
                <div class="step-to-pay">
                    <?= $block->escapeHtml(__('Link to Pay')); ?>
                </div>
                <div class="ticket-link">
                    <a target="_blank"
                        href="<?=  $block->escapeHtml($externalLink) ?>" 
                        alt="<?= /* @noEscape */ $title ?>"><?= $block->escapeHtml(__('Download the Ticket')); ?></a>
                </div>
            </div>
        <?php endif;?>
        <?php if ($financialInstitution): ?>
            <div class="instruction-information ticket-more-information">
                <div class="label">
                    <?= $block->escapeHtml(__('Financial Institution')); ?>
                </div>
                <div class="value">
                    <?=  $block->escapeHtml($financialInstitution) ?>
                </div>
            </div>
        <?php endif;?>
        <?php if ($payerFirstName): ?>
            <div class="instruction-information ticket-more-information">
                <div class="label">
                    <?= $block->escapeHtml(__('Issued on behalf of')); ?>
                </div>
                <div class="value">
                    <?=  $block->escapeHtml($payerFirstName) ?> <?=  $block->escapeHtml($payerLastName) ?>
                </div>
            </div>
        <?php endif;?>
        <?php if ($payerDocumentIdentification): ?>
            <div class="instruction-information ticket-more-information">
                <div class="label">
                    <?= $block->escapeHtml(__('Payer Document Identification')); ?>
                </div>
                <div class="value">
                    <?=  $block->escapeHtml($payerDocumentIdentification) ?>
                </div>
            </div>
        <?php endif;?>
        <?php if ($verificationCode): ?>
            <div class="instruction-information ticket-more-information">
                <div class="label">
                    <?= $block->escapeHtml(__('Verification Code')); ?>
                </div>
                <div class="value">
                    <?=  $block->escapeHtml($verificationCode) ?>
                </div>
            </div>
        <?php endif;?>
        
    </div>
<?php endif;?>
