<?php
/**
 * Copyright © MercadoPago. All rights reserved.
 *
 * @author      Bruno Elisei <brunoelisei@o2ti.com>
 * @license     See LICENSE for license details.
 */

/**
 * @var \MercadoPago\PaymentMagento\Block\Sales\Info\CheckoutPro $block
 * @see \MercadoPago\PaymentMagento\Block\Sales\Info\CheckoutPro
 */
$title = $block->escapeHtml($block->getMethod()->getTitle());
$specificInfo = $block->getSpecificInformation();
$mpPaymentType = isset($specificInfo['mp_payment_type_id']) ? $specificInfo['mp_payment_type_id']: null;
$mpInstallments = isset($specificInfo['mp_installments']) ? $specificInfo['mp_installments']: null;
$mpPaymentId = isset($specificInfo['mp_payment_id']) ? $specificInfo['mp_payment_id']: null;
$expirationDate = isset($specificInfo['date_of_expiration']) ? $specificInfo['date_of_expiration'] : null;
$externalLink = isset($specificInfo['init_point']) ? $specificInfo['init_point'] : null;
$ticketUrl = isset($specificInfo['ticket_url']) ? $specificInfo['ticket_url'] : null;
$status = isset($specificInfo['mp_status']) ? $specificInfo['mp_status'] : null;
$statusDetail = isset($specificInfo['mp_status_detail']) ? $specificInfo['mp_status_detail'] : null;
?>
<?php if ($specificInfo): ?>
    <table class="admin__table-secondary order-information-table">
        <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
        <tbody>
            <?php if ($mpPaymentId): ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('mp_payment_id')); ?></th>
                    <td><?= $block->escapeHtml($mpPaymentId); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($mpPaymentType): ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('Payment Type (Mercado Pago)')); ?></th>
                    <td><?= $block->escapeHtml($mpPaymentType); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($mpInstallments): ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('Installments (Mercado Pago)')); ?></th>
                    <td><?= $block->escapeHtml($mpInstallments); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($expirationDate): ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('Expiration')); ?></th>
                    <td>
                        <?= /* @noEscape */ $block->formatDate(
                            $expirationDate,
                            \IntlDateFormatter::MEDIUM,
                            false
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($externalLink): ?>
                <tr>
                    <th scope="row">
                        <?= $block->escapeHtml(__('Link')); ?>
                    </th>
                    <td>
                        <a target="_blank"
                            href="<?=  $block->escapeHtml($externalLink) ?>" 
                            alt="<?= /* @noEscape */ $title ?>">
                            <?= $block->escapeHtml(__('Details for payment')); ?>
                        </a>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($status): ?>
                <tr>
                    <th scope="row">
                        <?= $block->escapeHtml(__('Status (Mercado Pago)')); ?>
                    </th>
                    <td>
                        <?= $block->escapeHtml(__($status)) ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($statusDetail): ?>
                <tr>
                    <th scope="row">
                        <?= $block->escapeHtml(__('Status Detail (Mercado Pago)')); ?>
                    </th>
                    <td>
                        <?= $block->escapeHtml($statusDetail) ?>
                    </td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
<?php endif;?>