<?php

/**
 * Copyright © MercadoPago. All rights reserved.
 *
 * @license     See LICENSE for license details.
 */

/**
 * @var \MercadoPago\AdbPayment\Block\Sales\Info\Card $block
 * @see \MercadoPago\AdbPayment\Block\Sales\Info\Card
 */
$title = $block->escapeHtml(__($block->getMethod()->getTitle()));
$specificInfo = $block->getSpecificInformation();
$mpPaymentId = isset($specificInfo['mp_payment_id']) ? $specificInfo['mp_payment_id'] : null;
?>
<?php if ($specificInfo) : ?>
    <table class="admin__table-secondary order-information-table">
        <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
        <tbody>
            <?php if ($mpPaymentId) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('mp_payment_id')); ?></th>
                    <td><?= $block->escapeHtml($mpPaymentId); ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['card_payment_id'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('mp_payment_id')); ?>:</th>
                    <td><?= $block->escapeHtml($specificInfo['card_payment_id']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['card_installments'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('card_installments')); ?>:</th>
                    <td><?= $block->escapeHtml($specificInfo['card_installments']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['card_finance_cost'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('card_finance_cost')); ?>:</th>
                    <td><?= $block->getFormatedPrice($specificInfo['card_finance_cost']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['card_type'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('card_type')); ?>:</th>
                    <td><?= $block->escapeHtml($specificInfo['card_type']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['card_number'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('card_number')); ?>:</th>
                    <td><?= $block->escapeHtml($specificInfo['card_number']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['card_holder_name'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('card_holder_name')); ?>:</th>
                    <td><?= $block->escapeHtml($specificInfo['card_holder_name']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['card_exp_month'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('card_exp_month')); ?>:</th>
                    <td><?= $block->escapeHtml($specificInfo['card_exp_month']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['card_exp_year'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('card_exp_year')); ?>:</th>
                    <td><?= $block->escapeHtml($specificInfo['card_exp_year']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['payer_document_type'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('payer_document_type')); ?>:</th>
                    <td><?= $block->escapeHtml($specificInfo['payer_document_type']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['payer_document_identification'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('payer_document_identification')); ?>:</th>
                    <td><?= $block->escapeHtml($specificInfo['payer_document_identification']) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['mp_status'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('mp_status')); ?>:</th>
                    <td><?= $block->escapeHtml(__($specificInfo['mp_status'])) ?></td>
                </tr>
            <?php endif; ?>
            <?php if (isset($specificInfo['mp_status_detail'])) : ?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('mp_status_detail')); ?>:</th>
                    <td><?= $block->escapeHtml(__($specificInfo['mp_status_detail'])) ?></td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
<?php endif; ?>
