name: Validate Versions

on: [pull_request]

jobs:
  validate-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: "8.1"
          tools: composer

      - name: Verify PHP Installation
        run: php -v

      - name: Validate Composer
        run: composer validate

      - name: Validate Version
        run: bash bin/validate-version.sh
